import pandas as pd
import numpy as np
stockdata = pd.read_csv("dow_jones_index.data", parse_dates=['date'], index_col=['date'], nrows=100)
# print(stockdata.head())
# print(max(stockdata['volume']))
# print(max(stockdata['percent_change_price']))
# print(stockdata.index)
# print(stockdata.index.day)
# print(stockdata.index.month)
# print(stockdata.index.year)
# print(stockdata.resample('M').sum())
# print(stockdata.drop(["percent_change_volume_over_last_wk"], axis=1))
stockdata_new = pd.DataFrame(stockdata, columns = ["stock","open","high","low","close","volume"])
# print(stockdata_new.head())
stockdata.dropna().head(2)
# print(stockdata_new.open.describe())
stockdata_new.open = pd.to_numeric(stockdata_new.open.str.replace('$', ""))
stockdata_new.close = pd.to_numeric(stockdata_new.close.str.replace('$', ""))
(stockdata_new.close - stockdata_new.open).infer_objects()

# print(stockdata_new.open.describe())
stockdata_new["newopen"] = stockdata_new.open.apply(lambda x: 0.8*x)
print(stockdata_new.newopen.head(5))
stockAA = stockdata_new.query('stock=="AA"')
print(stockAA.head())
